### ISSUE TITLE
Can't launch server http://<server-ip>:3000

### ISSUE THREAD

**Issue by AlexisIMichelas** [Chris3481/seedbox#4]
Hello, 

I can't launch the server : Access flood interface on http://<server-ip>:3000

What do you mean by server-ip, my ip? and by checking the ports listened to on my machine I can't find the 3000, I don't know what to do, can you help me please?

I work on Windows, thank you and congratulations for your work ! :)

**Comment by Chris3481** [comment]
Hello ! 

Sorry for my late reply. 

if you run the seedbox localy on your computer, you can use http://127.0.0.1:3000 to access flood interface. 

If you're running it on a raspberry pi or an other server, you shoud use the local ip adress of the machine. It should look like 198.168.x.x

Hope you mange to make it work ;)
